# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  dhand_finger_base_left_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  dhand_finger_base_right_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  dhand_finger_middle_left_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  dhand_finger_middle_middle_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  dhand_finger_middle_right_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  dhand_finger_top_left_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  dhand_finger_top_middle_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  dhand_finger_top_right_joint:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  joint_b:
    has_velocity_limits: true
    max_velocity: 3.8135445205
    has_acceleration_limits: false
    max_acceleration: 0
  joint_e:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
  joint_l:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
  joint_r:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
  joint_s:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
  joint_t:
    has_velocity_limits: true
    max_velocity: 5.8032199225
    has_acceleration_limits: false
    max_acceleration: 0
  joint_u:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0