# Choose the Arduino board
BOARD_TAG     		= uno

# Set the Serial port 
MONITOR_PORT  		= /dev/ttyACM0

# Set the Baudrate
MONITOR_BAUDRATE 	= 9600

# Include Arduino.mk
include /usr/share/arduino/Arduino.mk
